### ISSUE TITLE
local.namespace = local_root : AttributeError: 'str' object has no attribute 'id'

### ISSUE THREAD

**Issue by magowiz** [AtakamaLLC/cloudsync#373]
Hi,
I'm trying to use the example provided, [Example of a syncronization between two cloud providers](https://atakama-llc-cloudsync.readthedocs-hosted.com/en/latest/README.html#example-of-a-syncronization-between-two-cloud-providers) but it doesn't work, when it reaches instruction: `local.namespace = local_root` I got this stacktrace:
```
Traceback (most recent call last):
  File "*****/cs_sync.py", line 91, in <module>
    main()
  File "*****/cs_sync.py", line 41, in main
    local.namespace = local_root
  File "/***/python3.9/site-packages/cloudsync/providers/filesystem.py", line 327, in namespace
    self.namespace_id = namespace.id
AttributeError: 'str' object has no attribute 'id'
```
So it seems that return data from tempfile.mkdtemp(), which is a 'str', is not compatible with that assignement because lacks of 'id' attribute.
Some details :
python version : 3.9.5 
cloudsync libraries versions:
cloudsync==3.0.12
cloudsync_gdrive==2.0.0

**Comment by howufiger7** [comment]
Looks like the docs are a bit out of date -- the `namespace` property is now a `Namespace` object, not a plain str.

I think all you have to do to get it working is change line 41 to: `local.namespace_id = local_root`

**Comment by magowiz** [comment]
it fixes the error in that line, after that cloudsync can successfully create a folder with current timestamp in google drive but it hangs forever on while loop :
```
while not remote.exists_path(remote_hello_path):
    time.sleep(1)
```
do I need to open another issue or we can go on here?

**Comment by howufiger7** [comment]
OK, I got the sample working on my end. Will update it on the doc site, and will likely need to fix the filesystem provider.  

The problem is that filesystem provider requires a "namespace" path and a root path. The namespace path needs to be absolute, the root path (and all other paths passed into it) need to be relative to the namespace path.

Ideally filesystem provider would not require a namespace at all, just a root path for syncing.

For now you can try the following:

23c23
< local.namespace = local_root  # filesystem provider wants to know the root namespace before connecting
---
> local.namespace_id = local_root  # filesystem provider wants to know the root namespace before connecting
32c32
< sync_roots = (local_root, remote_root)
---
> sync_roots = ("/", remote_root)
54c54
< local_goodbye_path = local.join(local_root, "goodbye.txt")
---
> local_goodbye_path = "goodbye.txt"

**Comment by magowiz** [comment]
yes this time it worked perfectly, thank you very much, I didn't know how to fix this
